daemon:
  enabled: false
  interval: 2
  interval_min: 1
integrations:
  elastic_siem:
    elastic_password: $ZS_INT_ELASTIC_PW
    elastic_url: https://localhost:9200
    elastic_user: elastic
    elastic_verify_certs: false
    enabled: false
    logging:
      log_level_file: debug
      log_level_stdout: debug
      log_level_syslog: error
  ibm_qradar:
    enabled: false
  vt_threat_intel:
    enabled: false
logging:
  language: en
  log_file_rotate_size: 1
  log_file_split: false
  log_file_split_module: false
  log_file_split_start: true
  log_level_file: debug
  log_level_stdout: info
  log_level_syslog: none
  split_file_on_startup: true
  split_file_on_worker_iteration: false
  split_files_by_module: false
setup:
  load_enviroment_variables: true
  setup_step: 0
znuny_otrs: null
