daemon:
  enabled: $zs_enable_daemon
  interval_min: 1
integrations:
  elastic_siem:
    elastic_password: $elastic_pw
    elastic_url: https://10.20.1.6:9200
    elastic_user: elastic
    elastic_verify_certs: false
    enabled: true
    logging:
      log_level_file: debug
      log_level_stdout: debug
      log_level_syslog: none
  ibm_qradar:
    enabled: false
  vt_threat_intel:
    enabled: false
logging:
  language: en
  log_file_rotate_size: 0
  log_level_file: debug
  log_level_stdout: info
  log_level_syslog: none
  split_file_on_startup: true
  split_file_on_worker_iteration: false
  split_files_by_module: false
setup:
  setup_step: 1
  load_enviroment_variables: true
znuny_otrs:
  api_customer_password: null
  api_customer_user: null
  hostname: null
  web_service_name: null
