daemon:
  enabled: false
  interval_min: 1
logging:
  language: en
  log_file_rotate_size: 0
  log_level_stdout: info
  log_level_syslog: none
  log_level_to_file: debug
  split_file_on_startup: true
  split_file_on_worker_iteration: false
setup:
  setup_step: 1
znuny_otrs:
  api_customer_password: null
  api_customer_user: null
  hostname: null
  web_service_name: null
