cache:
  file:
    enabled: true
    max_age_hours: 24
    max_size_mb: 10
    path: lib/cache.json
daemon:
  enabled: true
  interval: 1
  interval_min: 1
integrations:
  elastic_siem:
    elastic_password: $ZS_INT_ELASTIC_PW
    elastic_url: https://10.20.1.6:9200
    elastic_user: zsoar
    elastic_verify_certs: false
    enabled: true
    logging:
      log_level_file: info
      log_level_stdout: warning
      log_level_syslog: error
  ibm_qradar:
    enabled: false
    logging:
      log_level_file: debug
      log_level_stdout: debug
      log_level_syslog: error
    qradar_api_key: $ZS_INT_QRADAR_API_KEY
    qradar_url: https://10.20.1.1
    qradar_verify_certs: false
  virus_total:
    api_key: $ZS_INT_VIRUSTOTAL_API_KEY
    enabled: true
    logging:
      log_level_file: info
      log_level_stdout: warning
      log_level_syslog: error
    verify_certs: false
  znuny_otrs:
    context_provider:
      enabled: false
      itsm_customer: zsoar
    detection_provider:
      enabled: false
      source_queue: T1
    enabled: true
    logging:
      log_level_file: info
      log_level_stdout: warning
      log_level_syslog: error
    password: $ZS_INT_ZNUNY_PW
    ticketing:
      default_priority: 3 normal
      default_type: Security Alert
      enabled: true
      target_queue: ZSOAR Detections::Tests
      target_queue_escalation: ZSOAR Detections::Tests
    url: http://znuny.pve.lan
    username: zsoar
    verify_certs: false
    version: 7.0.1
    webservice_name: ALERTELAST_API
logging:
  language: en
  log_file_rotate_size: 1
  log_file_split: false
  log_file_split_module: false
  log_file_split_start: true
  log_level_file: info
  log_level_stdout: warning
  log_level_syslog: none
  split_file_on_startup: true
  split_file_on_worker_iteration: false
  split_files_by_module: false
playbooks:
  PB_010_Generic_Elastic_Alerts:
    enabled: true
  PB_110_Generic_VirusTotal:
    enabled: true
setup:
  load_enviroment_variables: true
  setup_step: 2
